// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4HwuOZ8Zw5-Zi8kgK3iEOaI7WRz1detI',
    appId: '1:341096488699:web:c342a50e8c17e7928c1a5e',
    messagingSenderId: '341096488699',
    projectId: 'trackerflutter-e61fb',
    authDomain: 'trackerflutter-e61fb.firebaseapp.com',
    storageBucket: 'trackerflutter-e61fb.firebasestorage.app',
    measurementId: 'G-0G5D4D6M1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW2u6I1hJ11Yn8zW-RDnjRorjXSpm8Lf4',
    appId: '1:341096488699:android:7c1f37d69cb475458c1a5e',
    messagingSenderId: '341096488699',
    projectId: 'trackerflutter-e61fb',
    storageBucket: 'trackerflutter-e61fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGV8LZ9oCNqo-lSye_5iAaEVlBERMeaQU',
    appId: '1:341096488699:ios:25b118d931432c7b8c1a5e',
    messagingSenderId: '341096488699',
    projectId: 'trackerflutter-e61fb',
    storageBucket: 'trackerflutter-e61fb.firebasestorage.app',
    iosBundleId: 'com.example.trackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGV8LZ9oCNqo-lSye_5iAaEVlBERMeaQU',
    appId: '1:341096488699:ios:25b118d931432c7b8c1a5e',
    messagingSenderId: '341096488699',
    projectId: 'trackerflutter-e61fb',
    storageBucket: 'trackerflutter-e61fb.firebasestorage.app',
    iosBundleId: 'com.example.trackerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4HwuOZ8Zw5-Zi8kgK3iEOaI7WRz1detI',
    appId: '1:341096488699:web:e10a8552751e5ea08c1a5e',
    messagingSenderId: '341096488699',
    projectId: 'trackerflutter-e61fb',
    authDomain: 'trackerflutter-e61fb.firebaseapp.com',
    storageBucket: 'trackerflutter-e61fb.firebasestorage.app',
    measurementId: 'G-10RYWENWY9',
  );
}
